### ISSUE TITLE
Multiple countries support

### ISSUE THREAD

**Issue by niewiemczego** [niewiemczego/nike-stock-monitor#2]
all eu, us + ca and others which use the same api

**Comment by niewiemczego** [comment]
added in newest update

**Comment by fengshuang0607** [comment]
Hello, can you add nike replenishment

**Comment by fengshuang0607** [comment]
MEDIUM 🟢- M 10.5 / W 12US
MEDIUM🟢 - M 11 / W 12.5US
LOW🟡 - M 12 / W 13.5US
LOW🟡 - M 12.5 / W 14US
LOW🟡 - M 13 / W 14.5US
OOS🔴 - M 14 / W 14.5US
If it can be done like this, it will be more clear
